#:kivy 1.0.9  

<Baddie>:
    name: self.name
    canvas:
        Ellipse:
            source: 'media/spinner.png'
            pos: self.pos
            size: self.size       

<Obstacle>:
    name: self.name
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<Background>:
    canvas.before:
        Rectangle:
            source: 'media/darkPurple.png'
            size: self.parent.size


<Player>:
    health: 20
    size: 50,50
    vel_x: 0
    vel_y: 0
    canvas:
        Rectangle:
            source: 'media/player.png'
            pos:self.pos
            size:self.size

<Game>:
    obstacle1: obstacle1
    obstacle2: obstacle2

    
    player: player

    Background:
        center: root.center
        size: self.parent.width, self.parent.height

    Obstacle:
        id: obstacle1
        pos: self.parent.center_x-5, 0
        size: 10, self.parent.height / 2

    Obstacle:
        id: obstacle2
        pos: self.parent.center_x + 25, 50
        size: 10, 10

    Baddie:
        pos: self.parent.height, 0
        size: 75, 75

    Label:
        font_size: 12  
        center_x: root.width / 12
        top: root.top
        text: "health: " + str(root.player.health)
    

    
    Player: 
        id: player
        center: self.parent.width/2 , self.parent.height * 3/4
